### ISSUE TITLE
Stop or Start a whole IIB application or Integration Server [feature-request]

### ISSUE THREAD

**Issue by simonalexander2005** [zheng-wang/irontest#13]
Currently, you can stop a message flow by filling in "Integration Server", "Application" and "Message Flow" for an IIB test case. 

If you leave "Message Flow" blank, it would be nice if the whole application could be stopped.

If you leave "Message Flow" and "Application" blank, it would be nice if the whole Integration Server could be stopped.

**Comment by zheng-wang** [comment]
Can I get more info about why an application or integration server need to be stopped as part of your testing?

If an application contains only one message flow, the current functionality can stop the message flow. If an application contains multiple message flows, testing all of them in one test case seems not a good practice. One test case is better to test one aspect of one message flow.

Stopping an integration server makes the test case impact even more.

**Comment by simonalexander2005** [comment]
> Can I get more info about why an application or integration server need to be stopped as part of your testing?
> One test case is better to test one aspect of one message flow.

You're right, in the most part just restarting the one message flow would suffice. The only time it would be helpful is if there are many message flows that contain cache data, and to clear the caches they would all have to be restarted - in which case it's more efficient to just restart the application

**Comment by zheng-wang** [comment]
Honestly, I haven't been able to figure out whether Iron Test should do test preparation like running MQ scripts to isolate a message flow, or starting/stopping message flow, etc. These look like deployment automation's scope. Before running automated tests, maybe deployment automation should go first to set up the environment for testing. This is because testing is data centric, and mixing deployment automation steps with data testing steps makes a test case cumbersome and lose focus.

The existing start/stop message flow feature was added early when I hadn't got good idea on message flow isolation. Later on, I think I got the idea, like shown in the [wiki](https://github.com/zheng-wang/irontest/wiki/IIB-Integration-Unit-Testing), so have removed usages of message flow start/stop steps from all my test cases. I was too lazy to remove the message flow start/stop feature.

So sorry I could not add application or integration server or even integration node or queue manager stop/start at this moment. In future when the Script Step feature is added to Iron Test, user would be able to write custom code to achieve these in Iron Test (though not recommended to do so). Let me know if I am wrong.

**Comment by zheng-wang** [comment]
For the cache scenario, I assume you are using the same cache across different message flows. Suggest to develop a simple message flow (CacheAdminMessageFlow) for clearing it, e.g. MQ Input -> Java Compute -> MQ Output. In the test case, instead of restart application or integration server to clear cache, just send a message to the CacheAdminMessageFlow for clearing the cache.

I may not be able to figure out the best solution for you, but code should be designed to be test friendly.

**Comment by simonalexander2005** [comment]
Thanks, I see your point that in an ideal world things would be done that way. When you're dealing with legacy code, or even just a test environment that you can't make structural changes to (like developing new flows, changing alias queues, etc.) then it can be harder to do this kind of testing in the ideal way. But I understand if you don't want to develop a new feature just for me ;)

**Comment by zheng-wang** [comment]
Right, developing a new feature for a single user and maintain the feature through the future is an effort that I am not able to afford. So I am closing this issue. Sorry about this.
