### ISSUE TITLE
Can I use IRON TEST as Auto-Testing.

### ISSUE THREAD

**Issue by Shiva143153** [zheng-wang/irontest#7]
1). So, I've performed some Unit Testing activities(Manually) in my DEV environment successfully using Iron Test. My question is, I want to process the flows in to QA using the Continues Integration. So once I build the flows and committed, can I make the IRON TEST as a dependency before releasing it in to QA?

2). Also, Here can I perform the Unit Testing actions as automatically ?

Will be helpful if you can respond for this, with some suggestions. 

Thanks.

**Comment by zheng-wang** [comment]
Thanks for the questions.

1). Iron Test has APIs that enable it to be integrated into CI pipeline. In the pipeline, at the point where you want to trigger Iron Test to test the flows (in QA env?), you can call the APIs to list all the test cases, run the test cases one by one and export the test reports (HTML format) to a location you like. The APIs are: 
- For getting the list of test cases: GET http://localhost:8081/api/foldertreenodes. It returns a JSON containing all folders and test cases in the Iron Test instance. It is currently used for displaying the folder tree on UI.
- For running one test case: POST http://localhost:8081/api/testcaseruns?testcaseId=<testcaseId\>. The response is a JSON containing run result for the whole test case and for each test step. <testcaseId\> can be obtained from the list of test cases from previous API.
- For exporting test report (HTML) of one test case run: GET http://localhost:8081/api/testcaseruns/<testcaseRunId\>/htmlreport. <testcaseRunId\> can be obtained from the run result from previous API.

Since I don't have a real world CI environment, I haven't used these APIs in CI by myself. So maybe the APIs are not enough or not providing best user experience. There is probably room for improvement. Especially, maybe Iron Test should support integration with popular CI engines (like Jenkins) without the need for programming.

2). Using the APIs mentioned above, you should be able to run test cases automatically. But for now, this requires programming, such as using JUnit/NUnit to call the APIs. Running multiple test cases in one go on UI (so as to avoid programming) is one of the features in my backlog. But because I am not using it frequently, its priority (for me) is low. Pull request is welcome. :)

**Comment by zheng-wang** [comment]
Assuming questions have been answered.
