### ISSUE TITLE
Queries 

### ISSUE THREAD

**Issue by Shiva-Gottimukkula** [zheng-wang/irontest#8]
Hi Wang,

So, I was trying to learn more about the IRON TEST for Auto Testing purpose. 

Here I have some initial queries.
1). Can't I Rename the Root Folder Name on the left
2). Can't I Delete the Test Cases or the Created Folders
3). Can you please brief me more about the start-team in the IRON TEST HOME.
     * Once after running the start-team cmd.exe
     * How I can give the Username and Password?(When I gave the Username and Password of 
        the one which give in IIB Test Case, It is popping an error-Invalid Details.)
     * Actually how am I supposed to Create One? 
4). What is the Main Purpose of the start-team? Was it like accessing like a repository?

**Comment by zheng-wang** [comment]
Hi Shiva, thanks for your queries.

1). Root folder name should be able to be renamed. There was a defect which I have fixed. Please rebuild the tool with latest release (v0.11.2).

2). Iron Test is designed currently to disable test case or folder deletion. This is to be enterprise friendly and avoid people accidentally deleting things and losing a lot of data. A 'recycle bin' feature could be deserved, but I haven't thought it over.
- My practice is to create an Archive folder, and move my useless test cases or folders there. I found many people practiced the same way in HP ALM, and I think it is a good practice to avoid losing too much data. By the way, test cases or folders in Archive folder can be reused if you like. For example, when creating a new test case, you can move one old test case from the Archive folder, and rename/edit it to be appropriate.

3). The start-team.bat is used to start Iron Test in team mode.
- By default (the start.bat), Iron Test is started in personal/individual mode which is supposed to be used by one person on local machine only. The instance is accessible only from localhost.
- Iron Test team mode is for team use. The instance is accessible from the LAN, so that multiple users can use the same instance from different machines at the same time. It makes Iron Test a typical web application. A team can be of any scale (less than 10 people in a small team, 10-100 people in a department or 100000 people for the entire enterprise).
- After running start-team.bat, you can login using the default admin account (username: sysadmin, password: password) via the Log In link in the upper right corner of the UI. Once you login with admin account, you can create other users using the Users menu item on the left panel (under Administration). This way, multiple users will have credentials to login the instance. Any user can change his/her password after logging in, via the upper right corner menu.
- Logged in user can create/edit things like test case, folder, environment, etc.
- Anyone without credentials is considered anonymous user. Anonymous user can view everything in the instance. He/she can not create/edit anything.

4). The purpose of start-team is for team collaboration.
- This is the way Iron Test uses to enable test cases/data to be shared between multiple people, and create an efficient collaboration platform for test automation.
- It avoids the need for the team to set up additional repository/mechanism for sharing the data like source control system (Git/Subversion/etc.). Source control system is not easy to set up, use and maintain, so Iron Test is trying to avoid it.
- However, please notice that team mode is an incomplete feature as of now. It has security enabled, but is lack of at least audit (change history) and concurrent editing. That is why I haven't created any documentation about it. To achieve a complete team mode feature, there is still a lot of work to do. I probably can only continue to develop it when I get a real-world team environment who is willing to trial it, and of course, enough spare time. : )

Let me know if you have more questions or requirements. I'll see what I can help.

**Comment by Shiva-Gottimukkula** [comment]
Sure! Thanks much for the quick response. This is helpful..

**Comment by zheng-wang** [comment]
Cool. I am closing this issue. Please raise new ones when you have new questions or requirements, so that we can have each issue with some focus.
