### ISSUE TITLE
Grep parts of result as input for other test steps

### ISSUE THREAD

**Issue by xadagaras** [zheng-wang/irontest#9]
Hi,

first of all, this is a very nice tooling for testing.

Currently I am trying to build a test case I have in postman, but in Iron Test. I am doing some rest calls which return a result. Then I need to wait a few minutes and after that I need to do another call, but I would need some input from previous requests.

Is is possible to save parts of the response in some property and use it in another test step? 

One way I could think of would be to add a Json Path like $.id and save it in ${Step1_Result} and use ${Step1_Result} in the other test step.

Regards

Daniel

**Comment by zheng-wang** [comment]
Thanks, this is definitely a must have feature in Iron Test. Every testing tool has it.

I am thinking about combining it with the existing UDP/DataTable features which hopefully won't get things too complicated.

I'll try to find some time to implement it, but due to other higher priority items, I'm not sure when that could happen. It would be great if you are able to craft some simple and initial POC, and we can discuss from there.

**Comment by zheng-wang** [comment]
Feature implemented. Refer to [Extracted Properties](https://github.com/zheng-wang/irontest/wiki/Properties#extracted-properties) for more information.
